[package]
name = "vds-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
vds-core = { path = "../../crates/vds-core" }
vds-device-model = { path = "../../crates/vds-device-model" }
vds-protocol = { path = "../../crates/vds-protocol" }
thiserror.workspace = true

[lints]
workspace = true
