[package]
name = "vds-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tokio.workspace = true
vds-core = { path = "../../crates/vds-core" }
vds-protocol = { path = "../../crates/vds-protocol" }
vds-scenario = { path = "../../crates/vds-scenario" }
vds-server = { path = "../vds-server" }

[lints]
workspace = true
